### ISSUE TITLE
can't find uiwpfdriver.exe

### ISSUE THREAD

**Issue by yfxiarigit** [RockFeng0/rock4automation#7]
当test = PcWpfTest() 的时候。报错
can't find uiwpfdriver.exe

**Comment by RockFeng0** [comment]
> 当test = PcWpfTest() 的时候。报错
> can't find uiwpfdriver.exe

参看下，安装说明，解压rock4-support-tools.zip，并设置环境变量。 uiwpfdriver.exe在这个压缩包里边
